STManager/urls.py
#from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import xadmin
from company.views import index

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('', index, name='index'),
    path('', include('products.urls', namespace='products')),
    path('', include('company.urls', namespace='company')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/company/urls.py
from django.urls import path
from .views import AddUserAskView, contactus, reply

app_name = 'company'

urlpatterns =[
    path('addask/', AddUserAskView.as_view(), name='add_ask'),
    path('contactus/', contactus, name='contactus'),
    path('reply_ask/<int:askid>/', reply, name='reply_ask'),
]

apps/products/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView, CaseListView,CaseDetailView

app_name = 'products'

urlpatterns =[
    path('products/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('cases/', CaseListView.as_view(), name='case_list'),
    path('cases/<int:pk>/', CaseDetailView.as_view(), name='case_detail'),
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/company/models.py
from datetime import datetime
from django.db import models
from django.core.exceptions import FieldError

from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class ContactInfo(models.Model):
    POSITION_CHOICES=(
        (0, '顶部'),
        (1, '边上'),
        (2, '其他'),
    )
    title = models.CharField('名称', max_length=20, blank=True, default='')
    info = models.CharField('联系信息', max_length=50)
    position = models.SmallIntegerField(verbose_name='位置', choices=POSITION_CHOICES, default=2)

    class Meta:
        verbose_name = '联系信息'
        verbose_name_plural = verbose_name
        unique_together = ('title', 'info', 'position')

    def __str__(self):
        return '{}{}'.format(self.title,self.info)

    def save(self, *args, **kwargs):
        '''顶部联系方式和边上联系方式 只能定义一个实例'''
        if self.position in (0,1):
            if self.title not in ('手机', '邮件'):
                raise FieldError('如果要定义 顶部或边上的联系方式，名称只能是 "手机" 或 "邮件" ')
            exist_obj = ContactInfo.objects.filter(position=self.position, title=self.title)
            if exist_obj:
                exist_obj.delete()
        super().save(*args, **kwargs)

class UserAsk(models.Model):
    '''用户咨询'''
    MESSAGE_STATUS_CHOICES=(
        (0, '未处理'),
        (1, '已处理'),
    )
    name = models.CharField('姓名', max_length=20)
    mobile = models.CharField('手机', max_length=11, blank=True)
    message = models.CharField('消息内容', max_length=500)
    email = models.EmailField('邮箱', max_length=50)
    add_date = models.DateTimeField('咨询时间',auto_now=True)
    due_date = models.DateTimeField('回复时间', blank=True, null=True)
    due_status = models.SmallIntegerField(verbose_name='咨询处理状态', choices=MESSAGE_STATUS_CHOICES, default=0)

    class Meta:
        verbose_name = '用户咨询'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def go_to(self):
        from django.utils.safestring import mark_safe
        # mark_safe后就不会转义
        url = reverse('company:reply_ask', kwargs={'askid': self.id})
        return mark_safe("<a href='" + url + "' target='_blank'>去处理</a>")

    go_to.short_description = "去处理"

class AskReply(models.Model):
    REPLY_CHOICES =(
        (0, '邮件'),
        (1, '非邮件'),
    )
    message = models.CharField('回复消息', max_length=500)
    user = models.ForeignKey(User, verbose_name='回复人', on_delete=models.SET_NULL, null=True)
    reply_method = models.SmallIntegerField(verbose_name='回复方式', choices=REPLY_CHOICES, default=0)
    user_ask = models.ForeignKey(UserAsk, verbose_name='用户咨询', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '留言回复'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '回复{}的留言'.format(self.user_ask.name)

apps/products/models.py
import os
from datetime import datetime
import uuid

from django.db import models
from DjangoUeditor.models import UEditorField

# Create your models here.
class Category(models.Model):
    '''产品类别'''
    name = models.CharField(max_length=30, verbose_name='产品类别', unique=True)

    class Meta:
        verbose_name = "产品类别"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class KeyWord(models.Model):
    '''产品关键字'''
    name = models.CharField(max_length=10, verbose_name='关键字')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "产品关键字"
        verbose_name_plural = verbose_name

def path_and_rename(instance, filename):
    upload_to = 'products'
    ext = filename.split('.')[-1].lower()
    if ext not in ['jpg', 'png', 'gif']:
        raise models.FieldError('we only support .jpg and .png imge')
    filename = "{}.{}".format(uuid.uuid4().hex[:10], ext)
    return os.path.join(upload_to, filename)

class Product(models.Model):
    '''产品'''
    category = models.ForeignKey(Category, verbose_name='所属类别', on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name='产品名')
    #desc = models.TextField(verbose_name='产品描述')
    brief = models.CharField(verbose_name='简单描述', default='', max_length=100)
    desc = UEditorField(verbose_name=u'产品描述', width=600, height=300, imagePath="products/ueditor/",
                          filePath="products/ueditor/", default='')
    image = models.ImageField(verbose_name='封面图', upload_to=path_and_rename, default='products/default.jpg', blank=True, null=True)
    author = models.CharField(verbose_name='作者', max_length=20, default=u'宋通轴承')
    views = models.PositiveIntegerField(verbose_name='热度', default=0)
    add_date = models.DateField(verbose_name='日期', auto_now_add=True)
    keywords = models.ManyToManyField(KeyWord, verbose_name='关键字', blank=True, null=True)

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "产品"
        verbose_name_plural = verbose_name

class Banner(models.Model):
    '''轮播图'''
    title = models.CharField('标题', max_length=100)
    image = models.ImageField('轮播图', upload_to='banner/%Y%m', max_length=100)  # /media/banner/xx
    index = models.IntegerField('顺序', default=100)  # 控制轮播顺序
    product = models.ForeignKey(Product, verbose_name='产品', on_delete=models.CASCADE) #首页可以访问的产品
    add_time = models.DateTimeField('添加时间', default=datetime.now)

    class Meta:
        verbose_name = "轮播图"
        verbose_name_plural = verbose_name

class Case(models.Model):
    '''技术支持'''
    title = models.CharField(max_length=50, verbose_name='文章名')
    brief = models.CharField(verbose_name='简单描述', default='', max_length=100)
    desc = UEditorField(verbose_name=u'文章内容', width=600, height=300, imagePath="supports/ueditor/",
                        filePath="supports/ueditor/", default='')
    author = models.CharField(verbose_name='作者', max_length=20, default=u'宋通轴承')
    views = models.PositiveIntegerField(verbose_name='热度', default=0)
    add_date = models.DateField(verbose_name='日期', auto_now_add=True)
    keywords = models.ManyToManyField(KeyWord, verbose_name='关键字', blank=True, null=True)

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "技术支持"
        verbose_name_plural = verbose_name

apps/products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.db.models import Q

from .models import Category, Product, Case

from apps.utils.global_vars import contact_info

# Create your views here.


class ProductListView(ListView):
    model = Product
    template_name = "products.html"
    paginate_by = 6

    def get_queryset(self):
        category_id = self.request.GET.get('ct', '')
        objs = Product.objects.all().order_by('-views')
        if category_id != '':
            objs = objs.filter(category__id=int(category_id))
        # 搜索功能
        search_keywords = self.request.GET.get('keywords', '')  # 搜索
        search_type = self.request.GET.get('type', '')
        if search_keywords:
            if search_type == 'category': # 类别只能选一个
                categories =  Category.objects.filter(name__icontains=search_keywords)
                if categories:
                    objs = Product.objects.filter(category__in=categories)
            elif search_type == 'product':
                objs = Product.objects.filter(Q(name__icontains=search_keywords) |
                                              Q(desc__icontains=search_keywords))
        return objs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        search_keywords = self.request.GET.get('keywords', '')  # 搜索
        search_type = self.request.GET.get('type', '')
        if search_type:
            if search_type == 'category':
                context['categories'] = Category.objects.filter(name__icontains=search_keywords)
            context['keywords'] = search_keywords
            context['type'] = search_type

        context['hots'] = Product.objects.all().order_by('-views')[:3]
        context['cur_category'] ='全部产品'
        category_id = self.request.GET.get('ct', '')
        if category_id != '':
            context['cur_category'] = Category.objects.get(id=int(category_id)).name
        return dict(context, **contact_info)

class ProductDetailView(DetailView):
    model = Product
    template_name = 'product.html'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.viewed()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hots'] = Product.objects.all().order_by('-views')[:3]
        all_category_products = Product.objects.filter(category_id=context['product'].category.id).order_by('id')
        context['pre_product'] = all_category_products.filter(id__lt=context['product'].id).first()
        context['next_product'] = all_category_products.filter(id__gt=context['product'].id).first()

        return dict(context,**contact_info)

class CaseListView(ListView):
    model = Case
    template_name = "cases.html"
    paginate_by = 20

    def get_queryset(self):
        objs = Case.objects.all().order_by('-views', '-add_date')
        # 搜索功能
        search_keywords = self.request.GET.get('keywords', '')  # 搜索
        search_type = self.request.GET.get('type', '')
        if search_keywords:
            if search_type == 'case':
               objs = objs.filter(Q(title__icontains=search_keywords) |
                                          Q(desc__icontains=search_keywords))
        return objs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hots'] = Product.objects.all().order_by('-views')[:3]
        search_keywords = self.request.GET.get('keywords', '')  # 搜索
        search_type = self.request.GET.get('type', '')
        if search_keywords:
            context['keywords'] = search_keywords
            context['type'] = search_type
        return dict(context,**contact_info)

class CaseDetailView(DetailView):
    model = Case
    template_name = 'case.html'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.viewed()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hots'] = Product.objects.all().order_by('-views')[:3]
        cases = Case.objects.all()
        context['pre_case'] = cases.filter(id__lt=context['case'].id).first()
        context['next_case'] = cases.filter(id__gt=context['case'].id).first()
        print(context['pre_case'])
        print(context['next_case'])
        return dict(context,**contact_info)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} 宋通首页 {% endblock %}</title>
    <!-- Bootstrap -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/index.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/iconfont.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/demo.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/base.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <!-- 头部 -->
  <div class="top visible-lg">
    <div class="container text-right">
      <ul class="list-inline">
        <li><i class="icon iconfont f16">&#xea42;</i> 电话:{{top_tel}}</li>
        <li><i class="icon iconfont f16">&#xea63;</i> 邮箱:{{top_email}}</li>
      </ul>
    </div>
  </div>
  <!-- 导航 -->
  <!-- 导航 -->
<nav class="navbar navbar-default navbar_style nomargin">
<div class="container">
<!--小屏幕导航按钮和logo -->
<div class="navbar-header">
<a href="{% url 'index' %}" class="navbar-brand visible-xs">开封宋通</a>
<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<!--小屏幕导航按钮和logo -->
<!-- 大屏幕显示导航 -->
<div class="navbar-collapse collapse">
<a class="visible-lg" href="#"><img class="nav_logo" src="{% static 'images/company/logo.png' %}" alt=""></a>
<ul class="nav navbar-nav navbar-right">
<li  {% if request.path == '/' %}class="active_nav" {% endif %}><a class="nav_title" href="{% url 'index' %} ">首页</a></li>
<li {% if request.path|slice:'9' == '/products' %}class="active_nav"{% endif %}><a class="nav_title" href="{% url 'products:product_list' %} ">产品中心</a></li>
<li {% if request.path|slice:'6' == '/cases' %}class="active_nav"{% endif %}><a class="nav_title" href="{% url 'products:case_list' %}">技术支持</a></li>
<li {% if request.path|slice:'10' == '/contactus' %}class="active_nav"{% endif %}><a class="nav_title" href="{% url 'company:contactus' %}">联系我们</a></li>
</ul>
</div>
<!-- 大屏幕显示 导航 --> 
</div>
</nav>
<!-- 导航结束 -->
<!-- banner -->  
<div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in all_banners %}
                            <li>
                                    <a href="{% url 'products:product_detail' banner.product.id %}">
                                        <img width="1200" height="400" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>
				</div>
			</div>
 <section id="search">
     <div class="container">
                <div class="wp">
                    <ol class="breadcrumb">位置:
          <li><a href="{% url 'index' %}">首页</a></li>
          <li class="active">{% block active_bread %}{% endblock %}</li>
        </ol>
                    <div class="searchbox fr" >
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="{% if type %} {{ type }} {% else %}product{% endif %}">
                              {% if type %}
                                 {% if type == 'category' %}
                                    类别
                                 {% endif %}
                                 {% if type == 'product' %}
                                    产品
                                 {% endif %}
                                 {% if type == 'case' %}
                                    技术支持
                                 {% endif %}
                              {% else %}
                                产品
                              {% endif %}
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="category">类别</li>
                                <li data-value="product">产品</li>
                                <li data-value="case">技术支持</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="{% if keywords %}{{ keywords }}{% endif %}" placeholder="请输入搜索内容" >
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'assets/img/search_btn.png' %}">
                    </div>
                </div>
            </div>
   </section>
  {% block body %} {% endblock %}
<!-- footer -->
<section id="footer">
  {% block footer %}
  <div class="container">
    <div class="col-sm-6 fl6">
      {% if request.path|slice:'10' == '/contactus' %}
      {% else %}
       <p>用户留言：</p>
      <form action="" id="jsStayForm">
        {% csrf_token %}
        <div class="form-group has-feedback footer_style">
          <input type="text" name="name" class="form-control" required placeholder="你的名字">
          <i class="icon iconfont form-control-feedback">&#xea59;</i>
        </div>
        <div class="form-group has-feedback footer_style">
          <input type="text" name="email" class="form-control" required placeholder="你的邮箱">
          <i class="icon iconfont form-control-feedback">&#xea63;</i>
        </div>
        <div class="form-group has-feedback footer_style">
          <input type="text"  name="mobile" class="form-control" required placeholder="你的联系方式">
          <i class="icon iconfont form-control-feedback">&#xea44;</i>
        </div>
        <div class="form-group has-feedback footer_style">
          <textarea class="form-control" name="message" rows="3"  required placeholder="你咨询的内容"></textarea>
          <i class="icon iconfont form-control-feedback">&#xea5f;</i>
        </div>
        <p class="error company-tips" id="jsCompanyTips" style="color:red;"></p>
        <button type="submit" class="btn pull-right" id="jsStayBtn">发送内容</button>
      </form>
      {% endif %}
    </div>
    <div class="col-sm-6 fr6">
      <p>联系我们</p>
      <ul class="list-unstyled mt30">
        {% for k,v in other_contacts.items %}
           <li>{{k}}: {{v}}</li>
        {% endfor %}
        <li>
          <ul class="list-inline">
            <li><a href="#"><img src="{% static 'assets/img/qq.png' %}" alt=""></a></li>
            <li><a href="#"><img src="{% static 'assets/img/message.png' %}" alt=""></a></li>
            <li><a href="#"><img src="{% static 'assets/img/phone.png' %}" alt=""></a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  {% endblock %}
</section>



<!-- 开始写代码 -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'assets/js/jquery-3.1.1.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/unslider.js' %}" type="text/javascript"></script>
  <script src="{% static 'assets/js/index.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
  /*小屏幕导航点击关闭导航菜单*/
    if(screen.width<1170){
      $(".navbar-collapse a").click(function(){
      $(".navbar-collapse").collapse("hide");
      });
    };

    //发送用户咨询
    $('#jsStayBtn').on('click', function(){
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'company:add_ask' %}",
                    data: $("#jsStayForm").serialize(),
                    async: true,
                    success: function(data){
                        if(data.status == 'success'){
                            $('#jsStayForm')[0].reset();
                             $('#jsCompanyTips').html('你的问题我们已经收到，将很快回复您')
                             alert("您的问题我们已经收到，将很快回复您")
                        }else if (data.status == 'fail'){
                            $('#jsCompanyTips').html(data.msg)
                        }
                    }
                });
            });
})

//顶部搜索栏搜索方法
function search_click(){
    var type = $('#jsSelectOption').attr('data-value'),
        keywords = $('#search_keywords').val(),
        request_url = '';
    if(keywords == ""){
        return
    }
    if(type == "category"){
        request_url = "/products/?type=category&keywords="+keywords
    }else if(type == "product"){
        request_url = "/products/?type=product&keywords="+keywords
    }else if(type == "case"){
        request_url = "/cases/?type=case&keywords="+keywords
    }
    window.location.href = request_url
}


//顶部搜索栏搜索按钮事件
    $('#jsSelectOption').on('click', function(){
        var $jsSelectMenu = $('#jsSelectMenu');
        if($jsSelectMenu.css('display') == 'block') return;
        $jsSelectMenu.addClass('dis');
    });
    $('#jsSelectMenu > li').on('click', function(){
        var searchType = $(this).attr('data-value'),
            searchName = $(this).text(),
            $jsSelectOption = $('#jsSelectOption');
        $jsSelectOption.attr('data-value',searchType).text(searchName);
        $(this).parent().removeClass('dis');
    });
    $(document).on('click', function(e){
        if(e.target != $('#jsSelectOption')[0] && e.target != $('#jsSelectMenu')[0]){
            $('#jsSelectMenu').removeClass('dis');
        }
    });


    $('#jsSearchBtn').on('click',function(){
        search_click()
    });

</script>

{% block custom_js %}
{% endblock %}
</body>
</html>

templates/case.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ case.name }}
{% endblock %}

{% block active_bread %}{{ case.name }}{% endblock %}

{% block body %}
<!-- case show -->
<section id="case">
  <div class="container">
    <div class="col-sm-9 case_details">
        <p class="case_title center" style="color:red;">{{ case.title }}</p>
        <div class="conauthor" style="margin-top: 10px;">[作者:{{ case.author }}]&nbsp;&nbsp;&nbsp;  [日期:{{case.add_date}}]&nbsp;&nbsp;&nbsp;   [热度:{{case.views }}]</div>
        <div style="margin-top: 20px; margin-bottom:20px;">
               {% autoescape off %}
                {{ case.desc }}
                {% endautoescape %}
        </div>
        <div  style=" margin-top:50px; margin-bottom:10px;">
           <span style="font-weight:bold;">关键字：</span> {% for keyword in product.keywords.all %}
                        {{ keyword.name }} ,
                    {% endfor %}
        </div>
        <div>
            上一篇：{% if pre_case %}
            <a href="{% url 'products:case_detail' pre_case.id %}">{{ pre_case.title }}</a>
            {% else %}
             没有了
            {% endif %}
        </div>
        <div>
            下一篇：{% if next_case %}
            <a href="{% url 'products:case_detail' next_case.id %}">{{next_case.title}}</a>
            {% else %}
             没有了
            {% endif %}
        </div>
    </div>
    <div class="col-sm-3">
      <p class="case_title">Hot products</p>
      <ul>
          {% for hot in hots %}
               <li>
          <a href="{% url 'products:product_detail' hot.id %}">
            <div class="case_cp"><a href="{% url 'products:product_detail' hot.id %}"><img src="{{MEDIA_URL}}{{ hot.image}}" alt=""></a> </div>
                <p>{{ hot.name }}</p>
          </a>
        </li>
          {% endfor %}
      </ul>
      <div class="contact_all">
         <p>电话:<span>{{ side_tel }}</span></p>
        <p>邮箱:<span>{{side_email}}</span></p>
        <img src="{% static 'assets/img/case_13.png' %}" alt="">
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <!-- in order to better provide quality product -->
<section id="do_better">
  <div class="container nopadding">
    <div class="col-sm-4 border pt15 pb15"><img class="img-responsive" src="{% static 'images/company/company.png' %}" alt=""></div>
    <div class="col-sm-8 pl40">
      <strong class="text-uppercase zhuse">公司介绍</strong>
      <div class="bs-example pl20" style="overflow:auto;">
        <p>{{ company_intro }}</p>
      </div>
      <div class="tip">
        <ul class="list-inline">
          <li>
            <a href="{% url 'products:case_list' %}">
            <img src="{% static 'assets/img/index_10.png' %}" alt="" title='技术支持'>
            </a>
          </li>
          <li>
            <a href="{% url 'products:product_list' %}">
            <img src="{% static 'assets/img/index_12.png'%}" alt="" title="产品列表">
            </a>
          </li>
          <li>
             <a href="{% url 'company:contactus' %}">
            <img src="{% static 'assets/img/index_14.png' %}" alt="" title="联系我们">
             </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

<!-- product -->
<section id="product">
  <div class="container">
    <p class="pro_title zhuse"><strong>— 热推产品 —</strong></p>
    {% for hot in hots %}
       <div class="col-sm-4 col-xs-6">
          <div class="pro_box"><img width="240px" height="120px" src="{{MEDIA_URL}}{{ hot.image}}"></div>
          <div class="caption">
            <strong class="db">{{ hot.name }}</strong>
            <p> {{ hot.brief }} </p>
            <p><span style="font-weight:bold;color:#006633;">产品类别</span>：
              <a href="/products/?ct={{hot.category.id }}">{{ hot.category.name }}</a> </p>
            <p><a href="{% url 'products:product_detail' hot.id %} " class="btn btn-huang" role="button">了解详情</a></p>
          </div>
    </div>
    {% endfor %}

  </div>
</section>
<!-- news -->
<section id="news">
  <div class="container">
    <p class="pro_title zhuse"><strong>— 热门技术支持 —</strong></p>
    <div class="col-sm-6"><img src="{% static 'assets/img/index_tu.png' %}"  width="100%" alt=""></div>
    <div class="col-sm-6">
      {% for case in hot_cases %}
          <div class="media">
        <a class="media-left" href="#">
          {{ forloop.counter  }}
        </a>
        <div class="media-body">
          <a href="{% url 'products:case_detail' case.id %}"><h4 class="media-heading zhuse"><strong>/ {{ case.title }} /</strong></h4></a>
          {{ case.brief }}……
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>